name: Generate Terraform Infrastructure Documentation From Plan

on:
  push:
    branches:
      - release/dev

  workflow_dispatch:

jobs:

  terraform-plan:

    runs-on: ubuntu-latest

    env:
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.0

      - name: Terraform Init
        working-directory: terraform-iaac
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform-iaac
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform-iaac
        run: terraform plan -out=tf-plan -input=false

      - name: Generate Terraform JSON
        working-directory: terraform-iaac
        run: terraform show -json tf-plan > tf-plan.json

      - name: Print Terraform JSON
        working-directory: terraform-iaac
        run: cat tf-plan.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # - name: Install OpenAI SDK
      #   run: pip install openai

      # - name: Generate Infrastructure Documentation
      #   env:
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #   run: python scripts/generate-doc.py

      - name: Install LLM SDK
        run: pip install litellm
        
      - name: Generate Infrastructure Documentation
        env:
          LLM_MODEL: gemini/gemini-3.5-flash-lite
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/generate-documentation.py


      - name: Upload Infrastructure Documentation
        uses: actions/upload-artifact@v4
        with:
          name: terraform-infrastructure-documentation
          path: infrastructure.md

      - name: Terraform Apply
        working-directory: terraform-iaac
        run: terraform apply -input=false tf-plan
        env:
            TF_LOG: INFO
